/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACompTypevar extends PTypevar
{
    private TId _id_;
    private final LinkedList<PComp> _comp_ = new LinkedList<PComp>();

    public ACompTypevar()
    {
        // Constructor
    }

    public ACompTypevar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _comp_)
    {
        // Constructor
        setId(_id_);

        setComp(_comp_);

    }

    @Override
    public Object clone()
    {
        return new ACompTypevar(
            cloneNode(this._id_),
            cloneList(this._comp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompTypevar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PComp> getComp()
    {
        return this._comp_;
    }

    public void setComp(List<?> list)
    {
        for(PComp e : this._comp_)
        {
            e.parent(null);
        }
        this._comp_.clear();

        for(Object obj_e : list)
        {
            PComp e = (PComp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comp_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._comp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._comp_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PComp> i = this._comp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
