/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADeclList extends PDeclList
{
    private PDeclList _declList_;
    private PDecl _decl_;

    public ADeclList()
    {
        // Constructor
    }

    public ADeclList(
        @SuppressWarnings("hiding") PDeclList _declList_,
        @SuppressWarnings("hiding") PDecl _decl_)
    {
        // Constructor
        setDeclList(_declList_);

        setDecl(_decl_);

    }

    @Override
    public Object clone()
    {
        return new ADeclList(
            cloneNode(this._declList_),
            cloneNode(this._decl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclList(this);
    }

    public PDeclList getDeclList()
    {
        return this._declList_;
    }

    public void setDeclList(PDeclList node)
    {
        if(this._declList_ != null)
        {
            this._declList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declList_ = node;
    }

    public PDecl getDecl()
    {
        return this._decl_;
    }

    public void setDecl(PDecl node)
    {
        if(this._decl_ != null)
        {
            this._decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declList_)
            + toString(this._decl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declList_ == child)
        {
            this._declList_ = null;
            return;
        }

        if(this._decl_ == child)
        {
            this._decl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declList_ == oldChild)
        {
            setDeclList((PDeclList) newChild);
            return;
        }

        if(this._decl_ == oldChild)
        {
            setDecl((PDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
