/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpArithExpression extends PExpression
{
    private PExpArith _expArith_;

    public AExpArithExpression()
    {
        // Constructor
    }

    public AExpArithExpression(
        @SuppressWarnings("hiding") PExpArith _expArith_)
    {
        // Constructor
        setExpArith(_expArith_);

    }

    @Override
    public Object clone()
    {
        return new AExpArithExpression(
            cloneNode(this._expArith_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpArithExpression(this);
    }

    public PExpArith getExpArith()
    {
        return this._expArith_;
    }

    public void setExpArith(PExpArith node)
    {
        if(this._expArith_ != null)
        {
            this._expArith_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expArith_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expArith_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expArith_ == child)
        {
            this._expArith_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expArith_ == oldChild)
        {
            setExpArith((PExpArith) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
