/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AStmtSelectIfStatement extends PStatement
{
    private PExpLogic _expLogic_;
    private PStatement _statement_;

    public AStmtSelectIfStatement()
    {
        // Constructor
    }

    public AStmtSelectIfStatement(
        @SuppressWarnings("hiding") PExpLogic _expLogic_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setExpLogic(_expLogic_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AStmtSelectIfStatement(
            cloneNode(this._expLogic_),
            cloneNode(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtSelectIfStatement(this);
    }

    public PExpLogic getExpLogic()
    {
        return this._expLogic_;
    }

    public void setExpLogic(PExpLogic node)
    {
        if(this._expLogic_ != null)
        {
            this._expLogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogic_ = node;
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogic_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogic_ == child)
        {
            this._expLogic_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogic_ == oldChild)
        {
            setExpLogic((PExpLogic) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
