/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVarDecl extends PVarDecl
{
    private PTypeDecl _typeDecl_;
    private PVarDeclId _varDeclId_;
    private TScolon _scolon_;

    public AVarDecl()
    {
        // Constructor
    }

    public AVarDecl(
        @SuppressWarnings("hiding") PTypeDecl _typeDecl_,
        @SuppressWarnings("hiding") PVarDeclId _varDeclId_,
        @SuppressWarnings("hiding") TScolon _scolon_)
    {
        // Constructor
        setTypeDecl(_typeDecl_);

        setVarDeclId(_varDeclId_);

        setScolon(_scolon_);

    }

    @Override
    public Object clone()
    {
        return new AVarDecl(
            cloneNode(this._typeDecl_),
            cloneNode(this._varDeclId_),
            cloneNode(this._scolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDecl(this);
    }

    public PTypeDecl getTypeDecl()
    {
        return this._typeDecl_;
    }

    public void setTypeDecl(PTypeDecl node)
    {
        if(this._typeDecl_ != null)
        {
            this._typeDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDecl_ = node;
    }

    public PVarDeclId getVarDeclId()
    {
        return this._varDeclId_;
    }

    public void setVarDeclId(PVarDeclId node)
    {
        if(this._varDeclId_ != null)
        {
            this._varDeclId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclId_ = node;
    }

    public TScolon getScolon()
    {
        return this._scolon_;
    }

    public void setScolon(TScolon node)
    {
        if(this._scolon_ != null)
        {
            this._scolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._scolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDecl_)
            + toString(this._varDeclId_)
            + toString(this._scolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDecl_ == child)
        {
            this._typeDecl_ = null;
            return;
        }

        if(this._varDeclId_ == child)
        {
            this._varDeclId_ = null;
            return;
        }

        if(this._scolon_ == child)
        {
            this._scolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeDecl_ == oldChild)
        {
            setTypeDecl((PTypeDecl) newChild);
            return;
        }

        if(this._varDeclId_ == oldChild)
        {
            setVarDeclId((PVarDeclId) newChild);
            return;
        }

        if(this._scolon_ == oldChild)
        {
            setScolon((TScolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
